version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: hashfish_mariadb2
    environment:
      MYSQL_DATABASE: ${dbname}
      MYSQL_ROOT_PASSWORD: ${dbpassword}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: harksulim/hashfish:2
    container_name: hashfish2
    environment:
      DB_HOST: ${dbhost}
      DB_PORT: 3306
      DB_USER: ${dbuser}
      DB_PASSWORD: ${dbpassword}
      DB_NAME: ${dbname}
      MASTER_EMAIL: ${master_email}
      MASTER_APIKEY: ${master_apikey}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "sleep 10 && /app/start.sh"

volumes:
  db_data:
