version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: hashfish_mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    # image: harksulim/fish-hash:latest
    image: eeche/fish-hash-server:latest
    container_name: hashfish
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MASTER_EMAIL: ${MASTER_EMAIL}
      MASTER_APIKEY: ${MASTER_APIKEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["python3", "server/main.py"]

volumes:
  db_data:
