version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: hashfish_mariadb
    environment:
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bob  # 여기서 'bob' 데이터베이스를 미리 생성
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    

  app:
    build: .
    container_name: hashfish
    command: uvicorn api:app --host 0.0.0.0 --port 8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: bob
      MASTER_EMAIL: "secure_master@example.com"
      MASTER_APIKEY: "super_secure_master_apikey"
    ports:
      - "8080:8080"
    depends_on:
      - db
        
    volumes:
      - .:/app

volumes:
  db_data:
