version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: hashfish_mariadb
    environment:
      MYSQL_DATABASE: bob
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  app:
    image: hashfish:latest
    container_name: hashfish
    environment:
      DB_HOST: db  # MariaDB 서비스의 이름을 사용해야 합니다.
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: bob
      MASTER_EMAIL: "secure_master@example.com"
      MASTER_APIKEY: "super_secure_master_apikey"
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "sleep 5 && /app/start.sh"

volumes:
  db_data:
